---
# file: tasks/set-role-variables.yml
# Set necessary mysqld-exporter role variables.

# Define how to handle mysqld-exporter service
- block:

  - name: Use systemd for CentOS >= 7
    set_fact:
      prometheus_mysqld_exporter_use_systemd: true
    when: ansible_distribution == "CentOS" and ansible_distribution_version|int >= 7

  - name: Use systemd for RHEL >= 7
    set_fact:
      prometheus_mysqld_exporter_use_systemd: true
    when: ansible_distribution == "Red Hat Enterprise Linux" and ansible_distribution_version|int >= 7

  - name: Use systemd for Debian >= 8
    set_fact:
      prometheus_mysql_exporter_use_systemd: true
    when: ansible_distribution == "Debian" and ansible_distribution_version|int >= 8

  - name: Use systemd for Ubuntu >= 16.04
    set_fact:
      prometheus_mysqld_exporter_use_systemd: true
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version|int >= 16

  when: prometheus_mysqld_exporter_use_systemd is not defined

- name: Use traditional SysV init, otherwise
  set_fact:
    prometheus_mysqld_exporter_use_systemd: false
  when: prometheus_mysqld_exporter_use_systemd is not defined
